% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Aug-2021 15:20:10
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------
                                       

Darkness = Simulink.Parameter;
Darkness.Value = [];
Darkness.CoderInfo.StorageClass = 'Auto';
Darkness.Description = '';
Darkness.DataType = 'Enum: HLC';
Darkness.Min = [];
Darkness.Max = [];
Darkness.DocUnits = '';

Day_Time = Simulink.Parameter;
Day_Time.Value = [];
Day_Time.CoderInfo.StorageClass = 'Auto';
Day_Time.Description = '';
Day_Time.DataType = 'Enum: HLC';
Day_Time.Min = [];
Day_Time.Max = [];
Day_Time.DocUnits = '';

Distance = Simulink.Parameter;
Distance.Value = 20;
Distance.CoderInfo.StorageClass = 'Auto';
Distance.Description = '';
Distance.DataType = 'double';
Distance.Min = 0.1;
Distance.Max = 80;
Distance.DocUnits = '';

Down_Hill = Simulink.Parameter;
Down_Hill.Value = 0;
Down_Hill.CoderInfo.StorageClass = 'Auto';
Down_Hill.Description = '';
Down_Hill.DataType = 'double';
Down_Hill.Min = 0;
Down_Hill.Max = -45;
Down_Hill.DocUnits = '';

Express_Way = Simulink.Parameter;
Express_Way.Value = [];
Express_Way.CoderInfo.StorageClass = 'Auto';
Express_Way.Description = '';
Express_Way.DataType = 'Enum: HLC';
Express_Way.Min = [];
Express_Way.Max = [];
Express_Way.DocUnits = '';

Fog_Detected = Simulink.Parameter;
Fog_Detected.Value = [];
Fog_Detected.CoderInfo.StorageClass = 'Auto';
Fog_Detected.Description = '';
Fog_Detected.DataType = 'Enum: HLC';
Fog_Detected.Min = [];
Fog_Detected.Max = [];
Fog_Detected.DocUnits = '';

Fog_Lamp = Simulink.Parameter;
Fog_Lamp.Value = [];
Fog_Lamp.CoderInfo.StorageClass = 'Auto';
Fog_Lamp.Description = '';
Fog_Lamp.DataType = 'Enum: HLC';
Fog_Lamp.Min = [];
Fog_Lamp.Max = [];
Fog_Lamp.DocUnits = '';

Headlight_Off = Simulink.Parameter;
Headlight_Off.Value = [];
Headlight_Off.CoderInfo.StorageClass = 'Auto';
Headlight_Off.Description = '';
Headlight_Off.DataType = 'Enum: HLC';
Headlight_Off.Min = [];
Headlight_Off.Max = [];
Headlight_Off.DocUnits = '';

High_Way = Simulink.Parameter;
High_Way.Value = [];
High_Way.CoderInfo.StorageClass = 'Auto';
High_Way.Description = '';
High_Way.DataType = 'Enum: HLC';
High_Way.Min = [];
High_Way.Max = [];
High_Way.DocUnits = '';

High_beam = Simulink.Parameter;
High_beam.Value = [];
High_beam.CoderInfo.StorageClass = 'Auto';
High_beam.Description = '';
High_beam.DataType = 'Enum: HLC';
High_beam.Min = [];
High_beam.Max = [];
High_beam.DocUnits = '';

Ignition_Off = Simulink.Parameter;
Ignition_Off.Value = [];
Ignition_Off.CoderInfo.StorageClass = 'Auto';
Ignition_Off.Description = '';
Ignition_Off.DataType = 'Enum: HLC';
Ignition_Off.Min = [];
Ignition_Off.Max = [];
Ignition_Off.DocUnits = '';

Ignition_On = Simulink.Parameter;
Ignition_On.Value = [];
Ignition_On.CoderInfo.StorageClass = 'Auto';
Ignition_On.Description = '';
Ignition_On.DataType = 'Enum: HLC';
Ignition_On.Min = [];
Ignition_On.Max = [];
Ignition_On.DocUnits = '';

Inside_City_Road = Simulink.Parameter;
Inside_City_Road.Value = [];
Inside_City_Road.CoderInfo.StorageClass = 'Auto';
Inside_City_Road.Description = '';
Inside_City_Road.DataType = 'Enum: HLC';
Inside_City_Road.Min = [];
Inside_City_Road.Max = [];
Inside_City_Road.DocUnits = '';

Left_Side = Simulink.Parameter;
Left_Side.Value = [];
Left_Side.CoderInfo.StorageClass = 'Auto';
Left_Side.Description = '';
Left_Side.DataType = 'Enum: HLC';
Left_Side.Min = [];
Left_Side.Max = [];
Left_Side.DocUnits = '';

Low_Beam = Simulink.Parameter;
Low_Beam.Value = [];
Low_Beam.CoderInfo.StorageClass = 'Auto';
Low_Beam.Description = '';
Low_Beam.DataType = 'Enum: HLC';
Low_Beam.Min = [];
Low_Beam.Max = [];
Low_Beam.DocUnits = '';

No_Vehical_Detected = Simulink.Parameter;
No_Vehical_Detected.Value = [];
No_Vehical_Detected.CoderInfo.StorageClass = 'Auto';
No_Vehical_Detected.Description = '';
No_Vehical_Detected.DataType = 'Enum: HLC';
No_Vehical_Detected.Min = [];
No_Vehical_Detected.Max = [];
No_Vehical_Detected.DocUnits = '';

Outside_City_Road = Simulink.Parameter;
Outside_City_Road.Value = [];
Outside_City_Road.CoderInfo.StorageClass = 'Auto';
Outside_City_Road.Description = '';
Outside_City_Road.DataType = 'Enum: HLC';
Outside_City_Road.Min = [];
Outside_City_Road.Max = [];
Outside_City_Road.DocUnits = '';

Param3 = Simulink.Parameter;
Param3.Value = [];
Param3.CoderInfo.StorageClass = 'Auto';
Param3.Description = '';
Param3.DataType = 'Enum: HLC';
Param3.Min = [];
Param3.Max = [];
Param3.DocUnits = '';

Parking_Light = Simulink.Parameter;
Parking_Light.Value = [];
Parking_Light.CoderInfo.StorageClass = 'Auto';
Parking_Light.Description = '';
Parking_Light.DataType = 'Enum: HLC';
Parking_Light.Min = [];
Parking_Light.Max = [];
Parking_Light.DocUnits = '';

Rain_Detected = Simulink.Parameter;
Rain_Detected.Value = [];
Rain_Detected.CoderInfo.StorageClass = 'Auto';
Rain_Detected.Description = '';
Rain_Detected.DataType = 'Enum: HLC';
Rain_Detected.Min = [];
Rain_Detected.Max = [];
Rain_Detected.DocUnits = '';

Right_Side = Simulink.Parameter;
Right_Side.Value = [];
Right_Side.CoderInfo.StorageClass = 'Auto';
Right_Side.Description = '';
Right_Side.DataType = 'Enum: HLC';
Right_Side.Min = [];
Right_Side.Max = [];
Right_Side.DocUnits = '';

Rural_Road = Simulink.Parameter;
Rural_Road.Value = [];
Rural_Road.CoderInfo.StorageClass = 'Auto';
Rural_Road.Description = '';
Rural_Road.DataType = 'Enum: HLC';
Rural_Road.Min = [];
Rural_Road.Max = [];
Rural_Road.DocUnits = '';

Speed = Simulink.Parameter;
Speed.Value = 60;
Speed.CoderInfo.StorageClass = 'Auto';
Speed.Description = '';
Speed.DataType = 'int8';
Speed.Min = 0;
Speed.Max = 250;
Speed.DocUnits = '';

Tunnel_Road = Simulink.Parameter;
Tunnel_Road.Value = [];
Tunnel_Road.CoderInfo.StorageClass = 'Auto';
Tunnel_Road.Description = '';
Tunnel_Road.DataType = 'Enum: HLC';
Tunnel_Road.Min = [];
Tunnel_Road.Max = [];
Tunnel_Road.DocUnits = '';

Up_Hill = Simulink.Parameter;
Up_Hill.Value = 0;
Up_Hill.CoderInfo.StorageClass = 'Auto';
Up_Hill.Description = '';
Up_Hill.DataType = 'double';
Up_Hill.Min = 0;
Up_Hill.Max = 45;
Up_Hill.DocUnits = '';

Vehicle_Detected_Left = Simulink.Parameter;
Vehicle_Detected_Left.Value = [];
Vehicle_Detected_Left.CoderInfo.StorageClass = 'Auto';
Vehicle_Detected_Left.Description = '';
Vehicle_Detected_Left.DataType = 'Enum: HLC';
Vehicle_Detected_Left.Min = [];
Vehicle_Detected_Left.Max = [];
Vehicle_Detected_Left.DocUnits = '';

Vehicle_Detected_Right = Simulink.Parameter;
Vehicle_Detected_Right.Value = [];
Vehicle_Detected_Right.CoderInfo.StorageClass = 'Auto';
Vehicle_Detected_Right.Description = '';
Vehicle_Detected_Right.DataType = 'Enum: HLC';
Vehicle_Detected_Right.Min = [];
Vehicle_Detected_Right.Max = [];
Vehicle_Detected_Right.DocUnits = '';

Vehicle_Unlocked = Simulink.Parameter;
Vehicle_Unlocked.Value = [];
Vehicle_Unlocked.CoderInfo.StorageClass = 'Auto';
Vehicle_Unlocked.Description = '';
Vehicle_Unlocked.DataType = 'Enum: HLC';
Vehicle_Unlocked.Min = [];
Vehicle_Unlocked.Max = [];
Vehicle_Unlocked.DocUnits = '';

Vehicle_locked = Simulink.Parameter;
Vehicle_locked.Value = [];
Vehicle_locked.CoderInfo.StorageClass = 'Auto';
Vehicle_locked.Description = '';
Vehicle_locked.DataType = 'Enum: HLC';
Vehicle_locked.Min = [];
Vehicle_locked.Max = [];
Vehicle_locked.DocUnits = '';

Wheel_Angle = Simulink.Parameter;
Wheel_Angle.Value = 0;
Wheel_Angle.CoderInfo.StorageClass = 'Auto';
Wheel_Angle.Description = '';
Wheel_Angle.DataType = 'double';
Wheel_Angle.Min = -7;
Wheel_Angle.Max = 7;
Wheel_Angle.DocUnits = '';

